trainer:
  logger: false
  precision: "16-mixed"
  callbacks:
    - class_path: pathseg.external_eval.callbacks.SavePrototypeROIPredictionsCallback
      init_args:
        out_dir: /home/valentin/workspaces/pathseg-benchmark/reports/figures/anorak_ignite/test_94nr99wz
        num_classes_b: 7
        num_classes_a: 16
        save_figures: true
        save_pred_masks: false
        save_logits_pt: false
        save_compartment_logits_pt: false
        save_numpy_masks: false
        write_csv: true
