trainer:
  precision: "16-mixed" # or "bf16-mixed" for uni2 or 16-mixed for h-optimus
  max_steps: 40000
  val_check_interval: 1000
  check_val_every_n_epoch: null
  accumulate_grad_batches: 1
  logger:
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
    init_args:
      project: "pathseg-benchmark"
      group: ANORAK
      job_type: baseline
      tags:
        [
          "baseline",
          "20x",
          "896x896",
          "ANORAK+IGNITE",
          "multitask",
          "linear_decoder",
          "CustomTransforms",
          "h0-mini",
        ]
      save_dir: ./wandb
      log_model: false # avoid artifact uploads in debug
model:
  class_path: pathseg.training.multitask_semantic.TwoHeadSemantic
  init_args:
    freeze_encoder: True
    source_id_a: 0
    source_id_b: 1
    num_metrics: 2
    network:
      # class_path: pathseg.models.multitask_unetr.TwoHeadViTPyramidSeg
      class_path: pathseg.models.multitask_decoder.TwoHeadsLinearDecoder
      # class_path: pathseg.models.multitask_decoder.TwoHeadsLinearARefinedBDecoder
      init_args:
        encoder_id: "h0-mini"
        num_classes_a: 16
        num_classes_b: 7
    tiler:
      class_path: pathseg.training.tiler.GridPadTiler
      init_args:
        tile: 896
        stride: 448
        weighted_blend: true # or true
        pad_mode: "replicate" # optional; nice for images
        pad_value: 0.0
data:
  class_path: pathseg.datasets.multitask.MultiTaskConcatDataModule
  init_args:
    datasets:
      - name: IGNITE
        root: /home/valentin/workspaces/pathseg-benchmark/data/fss/ignite
        images_subdir: "images"
        masks_subdir: "masks_semantic"
        split_csv: "metadata.csv"
        source_id: 0
        num_classes: 16
        sampling_weight: 1.0
      - name: ANORAK
        root: /home/valentin/workspaces/pathseg-benchmark/data/fss/anorak
        images_subdir: "images"
        masks_subdir: "masks_semantic"
        split_csv: "split.csv"
        source_id: 1
        num_classes: 7
        sampling_weight: 1.0
    fold: 0
    img_size: [896, 896]
    prefetch_factor: 4
    num_workers: 0
    batch_size: 16
    transforms:
      # class_path: pathseg.datasets.transforms.HistoTransforms
      class_path: pathseg.datasets.transforms.CustomTransforms
      init_args:
        img_size: [896, 896]
        scale_range: [0.7, 1.4]
        # hed_p: 0.3
        # hed_h_shift_limit: 0.02
        # hed_e_shift_limit: 0.02
        # hsv_p: 0.1
        # hsv_hue_shift_limit: 0.02
        # hsv_sat_scale_limit: 0.05
        # hsv_val_scale_limit: 0.05
        # max_brightness_delta: 16
        # max_contrast_factor: 0.15
