trainer:
  precision: "16-mixed" # or "bf16-mixed" for uni2 or 16-mixed for h-optimus
  max_steps: 40000
  val_check_interval: 1000
  check_val_every_n_epoch: null
  accumulate_grad_batches: 1
  logger:
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
    init_args:
      project: "pathseg-benchmark"
      group: ANORAK
      job_type: baseline
      tags: ["baseline", "wahoo", "20x", "896x896", "ANORAK", "Linear"]
      save_dir: ./wandb
      log_model: false # avoid artifact uploads in debug
model:
  class_path: pathseg.training.linear_semantic.LinearSemantic
  init_args:
    freeze_encoder: False
    class_weights: [0.2, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    network:
      class_path: pathseg.models.linear_decoder.LinearDecoder
      init_args:
        encoder_id: "h0-mini"
    tiler:
      class_path: pathseg.training.tiler.GridPadTiler
      init_args:
        tile: 896
        stride: 448
        weighted_blend: true # or true
        pad_mode: "replicate" # optional; nice for images
        pad_value: 0.0
data:
  class_path: pathseg.datasets.anorak.ANORAK
  init_args:
    root: /home/valentin/workspaces/pathseg-benchmark/data/ANORAK_20x
    img_size: [896, 896]
    prefetch_factor: 4
    num_workers: 0
    batch_size: 16
    fold: 0
    epoch_repeat: 30
    transforms:
      class_path: pathseg.datasets.transforms.CustomTransforms
      init_args:
        img_size: [896, 896]
        scale_range: [0.8, 1.2]
        # disable_color_jitter: true
